replicaCount: 2
image:
  repository: saiteja065/web-app
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  hosts:
    - host: web.saiteja065.local
      paths:
        - path: /
          pathType: Prefix
