name: CI-CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: saiteja065/web-app
  AWS_REGION: ap-south-1
  CLUSTER_NAME: webapp-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Kubeconfig for EKS
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
          

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest ./app
          docker push $IMAGE_NAME:latest

      - name: set up Helm
        uses: azure/setp-helm@v3
      - name: Helm upgrade --install  
        run: |
          helm upgrade --install web-app helm-chart/ \ 
            --set image.repository=$IMAGE_NAME \
            --set image.tag=latest
