name: CI-CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: saiteja065/web-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest ./app
          docker push $IMAGE_NAME:latest

  deploy-to-k8s:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name webapp-cluster

      - name: Deploy via Helm
        run: |
          helm upgrade --install web-app ./helm-chart --namespace default --create-namespace
